server:
  port: 8088

dubbo:
  application:
    name: dubbo-test-provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.exceedy.dubbotest.dubbotestinterface.service